port: 2424
admin_port: 2525
log:
  level: "info"
rate_limiter:
  enabled: true
  num_requests: 100
request_limits:
  allow_setting_keys: false
  max_size_bytes: 10240 # 10K
  max_num_values: 10
  # dup: backend.redis.expiration
  # max_ttl_seconds: 3600
backend:
  type: "redis"
  redis:
    host: "redis" # same as service name in compose.yml
    port: 6379
    password: ""
    db: 0
    expiration: 10 # in Minutes
    tls:
      enabled: false
      insecure_skip_verify: false
compression:
  type: "snappy"
metrics:
  type: "none"
  prometheus:
    port: 8080
    namespace: "prebid"
    subsystem: "cache"
    timeout_ms: 100
    enabled: true
routes:
  allow_public_write: true
